name: taskly
description: "Aplicativo de gerenciamento de tarefas com Flutter, GetX e Firebase"

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.6.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_core: ^2.30.0
  firebase_auth: ^4.17.4
  cloud_firestore: ^4.15.8

  # State Management
  get: ^4.6.6

  # Local Storage
  shared_preferences: ^2.2.2
  get_storage: ^2.1.1

  # Internationalization & Date
  intl: ^0.19.0
  flutter_localizations:
    sdk: flutter

  # UI Helpers
  flutter_datetime_picker: ^1.5.1
  uuid: ^3.0.7

  # Icons
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

  build_runner: ^2.4.8

flutter:
  uses-material-design: true
  generate: true
