// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkeENGWYvSond9505Oy9YwoD0OoJ3YNxA',
    appId: '1:916355695120:web:67338eeac71c8602fcc095',
    messagingSenderId: '916355695120',
    projectId: 'taskly-d4824',
    authDomain: 'taskly-d4824.firebaseapp.com',
    storageBucket: 'taskly-d4824.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVssYRulu7vRdEqjS2VWZMx5LQx0KBWjk',
    appId: '1:916355695120:android:37e9b65ee4cec8d9fcc095',
    messagingSenderId: '916355695120',
    projectId: 'taskly-d4824',
    storageBucket: 'taskly-d4824.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMGxOqhafBrFAxExEeHX4QwEESwN7LArw',
    appId: '1:916355695120:ios:004447d739072b3dfcc095',
    messagingSenderId: '916355695120',
    projectId: 'taskly-d4824',
    storageBucket: 'taskly-d4824.firebasestorage.app',
    iosBundleId: 'com.example.taskly',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCMGxOqhafBrFAxExEeHX4QwEESwN7LArw',
    appId: '1:916355695120:ios:004447d739072b3dfcc095',
    messagingSenderId: '916355695120',
    projectId: 'taskly-d4824',
    storageBucket: 'taskly-d4824.firebasestorage.app',
    iosBundleId: 'com.example.taskly',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCkeENGWYvSond9505Oy9YwoD0OoJ3YNxA',
    appId: '1:916355695120:web:c60789bb0bb69b22fcc095',
    messagingSenderId: '916355695120',
    projectId: 'taskly-d4824',
    authDomain: 'taskly-d4824.firebaseapp.com',
    storageBucket: 'taskly-d4824.firebasestorage.app',
  );
}
